name: MechOn
channels:
  - conda-forge
dependencies:
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - bleach
  - brotlicffi
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - debugpy
  - decorator
  - defusedxml
  - executing
  - expat
  - h11
  - httpcore
  - httpx
  - idna
  - ipykernel
  - ipython
  - ipython_pygments_lexers
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - libffi
  - libsodium
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert-core
  - nbformat
  - nest-asyncio
  - notebook
  - notebook-shim
  - openjdk
  - openssl
  - overrides
  - packaging
  - pandocfilters
  - parso
  - pip=
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycparser
  - pygments
  - pysocks
  - python=3.11.13
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - pyyaml
  - pyzmq
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - setuptools
  - six=1.17.0
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - notebook
  - ipykernel
  - nbconvert
  - pip:
      - jsonpickle==4.1.1
      - networkx==3.5
      - owlready2==0.48
      - pyparsing==3.2.3
      - pyvis==0.3.2
      - rdflib==7.1.4
